# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b4f1d0d0b81f5b661d94b3e129e4721a5065fd1988dc101d20b890c6bb24c038a8a9f91bc53600c9a8f77b69c39e66e1ee4cfe8d6bd1da93f04ab4379c54de

test:
  secret_key_base: 322af33e69ad42254018b89c0510da391b075e42fce2f023ab6b6426a87726201055a10a8a159d92f8d05ab0aeefedbc36bf7847c3ba2bccfd155179a204b41f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
